- name: Ansible jobs create
  hosts: localhost
  vars:
    jenkins_url: "http://172.31.94.144:8080"
    jenkins_username: "admin"
    jenkins_password: "{{ lookup('aws_ssm', 'jenkins_password', region='us-east-1' ) }}"
  tasks:
    - name: create jenkins jobs - Frontend
      community.general.jenkins_job:
       config: "{{ lookup('file', 'job.xml') }}"
       name: Frontend
       password: "{{jenkins_password}}"
       url: "{{jenkins_url}}"

       user: "{{jenkins_username}}"


    - name: create jenkins jobs - backend
      community.general.jenkins_job:
            config: "{{ lookup('file', 'job.xml') }}"
            name: backend
            password: "{{jenkins_password}}"
            url: "{{jenkins_url}}"

            user: "{{jenkins_username}}"



    - name: create jenkins jobs - Expense Parameters
      community.general.jenkins_job:
            config: "{{ lookup('file', 'job.xml') }}"
            name: expense-parameters
            password: "{{jenkins_password}}"
            url: "{{jenkins_url}}"

            user: "{{jenkins_username}}"



    - name: create jenkins jobs - Expense Terraform
      community.general.jenkins_job:
            config: "{{ lookup('file', 'job.xml') }}"
            name: expense-terraform
            password: "{{jenkins_password}}"
            url: "{{jenkins_url}}"

            user: "{{jenkins_username}}"